<h1 class="text-2xl mb-5 font-bold text-center">About Poliscope</h1>
<h2 class="text-center text-xl mb-2 font-semibold">Purpose</h2>
<p class="text-center">
	This web app was created with the intention of helping voters make informed decisions in the 2024
	election.
</p>
<h2 class="text-center text-xl mb-2 font-semibold">Data Sources</h2>
<h3 class="text-center mb-2 font-semibold">Candidate Info</h3>
<p class="text-center">The data for each candidate was sourced originally from Ballotpedia.</p>
<p class="text-center">
	The text from each candidate's Ballotpedia entry was fed into ChatGPT with strict instructions to
	summarize and parse the content as close to the original as possible and restructure it into a
	specified JSON schema.
</p>
<p>
	The Policy Perspectives insights were generated by ChatGPT after being fed the candidate's
	Ballotpedia entry with strict instructions to analyze it from a left-leaning, centrist, and
	right-leaning context.
</p>
<p>
	You can view the data directly in the GitHub repository. If you see an issue with the data or
	would like to make a contribution, I encourage you to submit a GitHub Issue or create a Pull
	Request.
</p>
<h3 class="text-center mb-2 font-semibold">Key Issues</h3>
<p class="text-center">The data for top issues was sourced originally from XXX.</p>
